In [ ]:
import numpy as np
import pandas as pd
from tensorflow import keras
from keras import layers
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

In [ ]:
df = pd.read_csv("/content/iris.csv")
df.dropna()
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
lc = LabelEncoder()
df["species"] = lc.fit_transform(df["species"])
df.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [ ]:
X = df.iloc[:, 0:4]
Y = df.iloc[:, 4]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=4)

In [ ]:
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [ ]:
model = keras.Sequential([
    layers.Dense(256, input_shape=[4], activation="relu"),
    layers.Dense(128, activation="relu"),
    layers.Dense(64, activation="relu"),
    layers.Dense(3, activation="softmax")
])

In [ ]:
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

In [ ]:
model.fit(x_train, y_train, epochs=20)

Epoch 1/20
4/4 [==============================] - 1s 5ms/step - loss: 1.0166 - accuracy: 0.4250
Epoch 2/20
4/4 [==============================] - 0s 4ms/step - loss: 0.8535 - accuracy: 0.5333
Epoch 3/20
4/4 [==============================] - 0s 4ms/step - loss: 0.7418 - accuracy: 0.8333
Epoch 4/20
4/4 [==============================] - 0s 4ms/step - loss: 0.6402 - accuracy: 0.9333
Epoch 5/20
4/4 [==============================] - 0s 4ms/step - loss: 0.5601 - accuracy: 0.8417
Epoch 6/20
4/4 [==============================] - 0s 4ms/step - loss: 0.4779 - accuracy: 0.9417
Epoch 7/20
4/4 [==============================] - 0s 4ms/step - loss: 0.4223 - accuracy: 0.9417
Epoch 8/20
4/4 [==============================] - 0s 6ms/step - loss: 0.3723 - accuracy: 0.9417
Epoch 9/20
4/4 [==============================] - 0s 4ms/step - loss: 0.3382 - accuracy: 0.9583
Epoch 10/20
4/4 [==============================] - 0s 5ms/step - loss: 0.2983 - accuracy: 0.9750
Epoch 11/20
4/4 [==============================] - 0s 4ms/step - loss: 0.2705 - accuracy: 0.9750
Epoch 12/20
4/4 [==============================] - 0s 3ms/step - loss: 0.2490 - accuracy: 0.9500
Epoch 13/20
4/4 [==============================] - 0s 4ms/step - loss: 0.2240 - accuracy: 0.9667
Epoch 14/20
4/4 [==============================] - 0s 4ms/step - loss: 0.1891 - accuracy: 0.9667
Epoch 15/20
4/4 [==============================] - 0s 4ms/step - loss: 0.1786 - accuracy: 0.9667
Epoch 16/20
4/4 [==============================] - 0s 5ms/step - loss: 0.1558 - accuracy: 0.9750
Epoch 17/20
4/4 [==============================] - 0s 5ms/step - loss: 0.1480 - accuracy: 0.9750
Epoch 18/20
4/4 [==============================] - 0s 4ms/step - loss: 0.1344 - accuracy: 0.9667
Epoch 19/20
4/4 [==============================] - 0s 4ms/step - loss: 0.1177 - accuracy: 0.9750
Epoch 20/20
4/4 [==============================] - 0s 3ms/step - loss: 0.1098 - accuracy: 0.9833